apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-config
  annotations:
    'strategy.spinnaker.io/versioned': 'false'
data:
  SPRING_PROFILE: {{ .Values.springProfile }}
