{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: profile-vs
spec:
  hosts:
    - "*"
  gateways:
    - profile-gateway
  http:
    - route:
        - destination:
            host: {{.Values.serviceName}}
#            subset: v1
{{- end -}}