{{- if .Values.istio.enabled -}}
  apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: profile-gateway
  spec:
    selector:
      istio: ingressgateway # use Istio default gateway implementation
    servers:
      - port:
          name: http
          number: 80
          protocol: HTTP
        hosts:
          - {{.Values.istioHost}}
{{- end -}}