apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: profile-service
build:
  artifacts:
    - image: profile-service
      context: .
      docker:
        dockerfile: Dockerfile

deploy:
  helm:
    releases:
      - name: my-release
        chartPath: ./helm/profile
        valuesFiles:
          - ./helm/profile/values-develop.yaml
        artifactOverrides:
          image: profile-service
        imageStrategy:
          helm: {}
